[crate_name_overrides]
"web_kit2" = "webkit2"

[options]
girs_dir = "gir-files"
library = "WebKit2"
version = "4.0"
work_mode = "normal"
target_path = "."
generate_safety_asserts = true
single_version_file = true

external_libraries = [
    "Gio",
    "Gtk",
    "JavaScriptCore",
    "Soup"
]

generate = [
    "WebKit2.AuthenticationScheme",
    "WebKit2.BackForwardList",
    "WebKit2.BackForwardListItem",
    "WebKit2.CacheModel",
    "WebKit2.ColorChooserRequest",
    "WebKit2.ContextMenu",
    "WebKit2.ContextMenuAction",
    "WebKit2.ContextMenuItem",
    "WebKit2.CookieAcceptPolicy",
    "WebKit2.CookieManager",
    "WebKit2.CookiePersistentStorage",
    "WebKit2.Credential",
    "WebKit2.CredentialPersistence",
    "WebKit2.Download",
    "WebKit2.DownloadError",
    "WebKit2.EditorState",
    "WebKit2.EditorTypingAttributes",
    "WebKit2.FaviconDatabase",
    "WebKit2.FaviconDatabaseError",
    "WebKit2.FileChooserRequest",
    "WebKit2.FindController",
    "WebKit2.FindOptions",
    "WebKit2.FormSubmissionRequest",
    "WebKit2.GeolocationPermissionRequest",
    "WebKit2.HardwareAccelerationPolicy",
    "WebKit2.HitTestResult",
    "WebKit2.HitTestResultContext",
    "WebKit2.InsecureContentEvent",
    "WebKit2.InstallMissingMediaPluginsPermissionRequest",
    "WebKit2.JavascriptError",
    "WebKit2.JavascriptResult",
    "WebKit2.LoadEvent",
    "WebKit2.MimeInfo",
    "WebKit2.NavigationPolicyDecision",
    "WebKit2.NavigationType",
    "WebKit2.NetworkError",
    "WebKit2.NetworkProxyMode",
    "WebKit2.Notification",
    "WebKit2.NotificationPermissionRequest",
    "WebKit2.PermissionRequest",
    "WebKit2.Plugin",
    "WebKit2.PluginError",
    "WebKit2.PolicyDecision",
    "WebKit2.PolicyDecisionType",
    "WebKit2.PolicyError",
    "WebKit2.ProcessModel",
    "WebKit2.PrintCustomWidget",
    "WebKit2.PrintError",
    "WebKit2.PrintOperation",
    "WebKit2.PrintOperationResponse",
    "WebKit2.ResponsePolicyDecision",
    "WebKit2.SaveMode",
    "WebKit2.ScriptDialogType",
    "WebKit2.SecurityManager",
    "WebKit2.SecurityOrigin",
    "WebKit2.Settings",
    "WebKit2.SnapshotError",
    "WebKit2.SnapshotOptions",
    "WebKit2.SnapshotRegion",
    "WebKit2.TLSErrorsPolicy",
    "WebKit2.UserContentInjectedFrames",
    "WebKit2.UserContentManager",
    "WebKit2.UserMediaPermissionRequest",
    "WebKit2.UserScript",
    "WebKit2.UserScriptInjectionTime",
    "WebKit2.UserStyleLevel",
    "WebKit2.UserStyleSheet",
    "WebKit2.WebInspector",
    "WebKit2.WebResource",
    "WebKit2.WebsiteDataTypes",
    "WebKit2.WebViewBase",
    "WebKit2.WebViewSessionState",
    "WebKit2.WebsiteDataManager",
    "WebKit2.WindowProperties",
]

manual = [
    "cairo.Surface",
    "Gdk.Event",
    "Gdk.Rectangle",
    "Gdk.RGBA",
    "Gio.Cancellable",
    "Gio.InputStream",
    "Gio.TlsCertificate",
    "Gio.TlsCertificateFlags",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.List",
    "GLib.Variant",
    "GObject.Object",
    #"Gtk.Action",
    "Gtk.Container",
    "Gtk.FileFilter",
    "Gtk.PageSetup",
    "Gtk.PrintSettings",
    "Gtk.Widget",
    "Gtk.Window",
    "JavaScriptCore.GlobalContextRef",
    "JavaScriptCore.Value",
    "JavaScriptCore.ValueRef",
    "Soup.MessageHeaders",
    "WebKit2.ScriptDialog",
]

[[object]]
name = "WebKit2.AuthenticationRequest"
status = "generate"
    [[object.function]]
    name = "authenticate"
    ignore = true

[[object]]
name = "WebKit2.WebContext"
status = "generate"
    [[object.function]]
    name = "set_network_proxy_settings"
    ignore = true

[[object]]
name = "WebKit2.NetworkProxySettings"
status = "generate"
    [[object.function]]
    name = "new"
    ignore = true

[[object]]
name = "WebKit2.URISchemeRequest"
status = "generate"
module_name = "uri_scheme_request"

[[object]]
name = "WebKit2.URIRequest"
status = "generate"
module_name = "uri_request"

[[object]]
name = "WebKit2.URIResponse"
status = "generate"
module_name = "uri_response"

[[object]]
name = "WebKit2.WebView"
status = "generate"
    [[object.signal]]
    name = "create"
    version = "2.6"
        [object.signal.return]
        nullable = true

[[object]]
name = "WebKit2.NavigationAction"
status = "generate"
    [[object.function]]
    name = "get_modifiers"
        [[object.function.parameter]]
        name = "navigation"
        const = true
    [[object.function]]
    name = "get_mouse_button"
        [[object.function.parameter]]
        name = "navigation"
        const = true
    [[object.function]]
    name = "get_navigation_type"
        [[object.function.parameter]]
        name = "navigation"
        const = true
    [[object.function]]
    name = "get_request"
        [[object.function.parameter]]
        name = "navigation"
        const = true
    [[object.function]]
    name = "is_user_gesture"
        [[object.function.parameter]]
        name = "navigation"
        const = true
